### ISSUE TITLE
Bottleneck layer of the encoder

### ISSUE THREAD

**Issue by saniazahan** [shuuchen/video_autoencoder#2]
Hi I am trying to figure out the bottleneck layer of the AE model. Could you please indicate where in the code the layer is defined and how many units it has. Thanks.

**Comment by shuuchen** [comment]
Hi,

Both encoder and decoder are implemented with LSTM, there is no bottleneck
inside.

2020年10月7日(水) 22:34 Sania Zahan <notifications@github.com>:

**Comment by saniazahan** [comment]
But if there is no bottleneck layer the encoded version contains all information. Isn't it opposite to the motivation of using autoencoder?

**Comment by shuuchen** [comment]
what do you mean by 'contains all information' and why 'opposite to the motivation of using autoencoder' ?

please read the corresponding paper of this rep.
the encoded latent vectors are in the hidden state of lstms, where the dimension is reduced.

**Comment by saniazahan** [comment]
Oh got it. Thanks.
