### ISSUE TITLE
Learned vector patterns and movements

### ISSUE THREAD

**Issue by jpainam** [shuuchen/video_autoencoder#3]
Hi, would you mind sharing the code and the type of data that is expected to draw this?
Thank you.

![image](https://user-images.githubusercontent.com/1701705/143783624-448f6c8d-013d-4567-b474-619c9f3a8308.png)

**Comment by shuuchen** [comment]
Hi,

I don't have this file. You can use any videos as time series, embed the frames and put them in rows like this.

**Comment by jpainam** [comment]
I have a video, where each frame is represented as a vector (the embedding). what do you mean by putting them in rows?

**Comment by shuuchen** [comment]
OK. You can put each embedded vector as a row in an excel file to create your own training data.

**Comment by jpainam** [comment]
Thank you, I actually got this part. My concern is about the image, how did you plot it? which method from `matplotlib` can do that?

**Comment by shuuchen** [comment]
It is plotted with color scales in microsoft excel.
https://www.howtogeek.com/734938/how-to-apply-a-color-scale-based-on-values-in-microsoft-excel/

**Comment by jpainam** [comment]
Ok. gotcha
